### PR TITLE
update Makefile and vendor

### PR DESCRIPTION
**Pull request by carmark**

### CODE REVIEW

**Comment by tpaullee** [comment]
Lei,Vendor change is mostly because of Microsoft acquisition?There is a build area on the diff page.
/Paul

N 37-17.454 W 121-57.679 http://tpaullee.blogspot.com/ Cultivating Human Goodness 

    On Tuesday, October 30, 2018, 8:21:22 PM PDT, Lei Xue <notifications@github.com> wrote:  
 
 
You can view, comment on, or merge this pull request online at:

  https://github.com/gostor/gotgt/pull/75

Commit Summary
   
   - update vendor
   - update Makefile
   - update .travis.yml for build

File Changes
   
   -  M .gitignore (2) 
   -  M .travis.yml (3) 
   -  D Godeps/Godeps.json (68) 
   -  D Godeps/Readme (5) 
   -  D Godeps/_workspace/.gitignore (2) 
   -  D Godeps/_workspace/src/github.com/Sirupsen/logrus/entry_test.go (77) 
   -  D Godeps/_workspace/src/github.com/Sirupsen/logrus/examples/basic/basic.go (50) 
   -  D Godeps/_workspace/src/github.com/Sirupsen/logrus/examples/hook/hook.go (30) 
   -  D Godeps/_workspace/src/github.com/Sirupsen/logrus/formatter_bench_test.go (98) 
   -  D Godeps/_workspace/src/github.com/Sirupsen/logrus/formatters/logstash/logstash.go (63) 
   -  D Godeps/_workspace/src/github.com/Sirupsen/logrus/formatters/logstash/logstash_test.go (52) 
   -  D Godeps/_workspace/src/github.com/Sirupsen/logrus/hook_test.go (122) 
   -  D Godeps/_workspace/src/github.com/Sirupsen/logrus/hooks/syslog/README.md (39) 
   -  D Godeps/_workspace/src/github.com/Sirupsen/logrus/hooks/syslog/syslog.go (54) 
   -  D Godeps/_workspace/src/github.com/Sirupsen/logrus/hooks/syslog/syslog_test.go (26) 
   -  D Godeps/_workspace/src/github.com/Sirupsen/logrus/hooks/test/test.go (67) 
   -  D Godeps/_workspace/src/github.com/Sirupsen/logrus/hooks/test/test_test.go (39) 
   -  D Godeps/_workspace/src/github.com/Sirupsen/logrus/json_formatter_test.go (120) 
   -  D Godeps/_workspace/src/github.com/Sirupsen/logrus/logrus_test.go (361) 
   -  D Godeps/_workspace/src/github.com/Sirupsen/logrus/text_formatter_test.go (61) 
   -  D Godeps/_workspace/src/github.com/ceph/go-ceph/.travis.yml (26) 
   -  D Godeps/_workspace/src/github.com/ceph/go-ceph/Dockerfile (26) 
   -  D Godeps/_workspace/src/github.com/ceph/go-ceph/README.md (107) 
   -  D Godeps/_workspace/src/github.com/ceph/go-ceph/cephfs/cephfs.go (89) 
   -  D Godeps/_workspace/src/github.com/ceph/go-ceph/cephfs/cephfs_test.go (66) 
   -  D Godeps/_workspace/src/github.com/ceph/go-ceph/ci/before_install.sh (27) 
   -  D Godeps/_workspace/src/github.com/ceph/go-ceph/ci/entrypoint.sh (114) 
   -  D Godeps/_workspace/src/github.com/ceph/go-ceph/ci/micro-osd.sh (119) 
   -  D Godeps/_workspace/src/github.com/ceph/go-ceph/doc.go (9) 
   -  D Godeps/_workspace/src/github.com/ceph/go-ceph/package_test.go (12) 
   -  D Godeps/_workspace/src/github.com/ceph/go-ceph/rados/rados_test.go (1022) 
   -  D Godeps/_workspace/src/github.com/ceph/go-ceph/rbd/rbd_test.go (277) 
   -  D Godeps/_workspace/src/github.com/coreos/go-systemd/activation/files_test.go (82) 
   -  D Godeps/_workspace/src/github.com/coreos/go-systemd/activation/listeners_test.go (86) 
   -  D Godeps/_workspace/src/github.com/coreos/go-systemd/activation/packetconns_test.go (68) 
   -  D Godeps/_workspace/src/github.com/docker/docker/NOTICE (19) 
   -  D Godeps/_workspace/src/github.com/docker/go-connections/sockets/inmem_socket_test.go (39) 
   -  D Godeps/_workspace/src/github.com/gorilla/context/context_test.go (161) 
   -  D Godeps/_workspace/src/github.com/gorilla/mux/bench_test.go (21) 
   -  D Godeps/_workspace/src/github.com/gorilla/mux/mux_test.go (1003) 
   -  D Godeps/_workspace/src/github.com/gorilla/mux/old_test.go (714) 
   -  D Godeps/_workspace/src/github.com/satori/go.uuid/benchmarks_test.go (123) 
   -  D Godeps/_workspace/src/github.com/satori/go.uuid/uuid.go (481) 
   -  D Godeps/_workspace/src/github.com/satori/go.uuid/uuid_test.go (633) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/bash_completions_test.go (140) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/cobra/cmd/add.go (128) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/cobra/cmd/helpers.go (356) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/cobra/cmd/helpers_test.go (40) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/cobra/cmd/init.go (245) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/cobra/cmd/licenses.go (1384) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/cobra/cmd/root.go (72) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/cobra/main.go (20) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/cobra_test.go (1188) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/command_test.go (135) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/doc/cmd_test.go (145) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/doc/man_docs.go (218) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/doc/man_docs.md (26) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/doc/man_docs_test.go (161) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/doc/man_examples_test.go (35) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/doc/md_docs.go (175) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/doc/md_docs.md (104) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/doc/md_docs_test.go (88) 
   -  D Godeps/_workspace/src/github.com/spf13/cobra/doc/util.go (38) 
   -  D Godeps/_workspace/src/github.com/spf13/pflag/bool_test.go (180) 
   -  D Godeps/_workspace/src/github.com/spf13/pflag/count_test.go (55) 
   -  D Godeps/_workspace/src/github.com/spf13/pflag/example_test.go (77) 
   -  D Godeps/_workspace/src/github.com/spf13/pflag/export_test.go (29) 
   -  D Godeps/_workspace/src/github.com/spf13/pflag/flag_test.go (913) 
   -  D Godeps/_workspace/src/github.com/spf13/pflag/golangflag_test.go (39) 
   -  D Godeps/_workspace/src/github.com/spf13/pflag/int_slice_test.go (162) 
   -  D Godeps/_workspace/src/github.com/spf13/pflag/ip_test.go (63) 
   -  D Godeps/_workspace/src/github.com/spf13/pflag/ipnet_test.go (70) 
   -  D Godeps/_workspace/src/github.com/spf13/pflag/string_slice_test.go (161) 
   -  D Godeps/_workspace/src/github.com/spf13/pflag/verify/all.sh (69) 
   -  D Godeps/_workspace/src/github.com/spf13/pflag/verify/gofmt.sh (19) 
   -  D Godeps/_workspace/src/github.com/spf13/pflag/verify/golint.sh (15) 
   -  D Godeps/_workspace/src/golang.org/x/net/context/context_test.go (575) 
   -  D Godeps/_workspace/src/golang.org/x/net/context/withtimeout_test.go (26) 
   -  D Godeps/_workspace/src/golang.org/x/net/proxy/per_host_test.go (55) 
   -  D Godeps/_workspace/src/golang.org/x/net/proxy/proxy_test.go (142) 
   -  A Gopkg.lock (129) 
   -  A Gopkg.toml (42) 
   -  D Makefile.am (10) 
   -  M README.md (2) 
   -  D autogen.sh (35) 
   -  D configure.ac (60) 
   -  R vendor/github.com/Microsoft/go-winio/LICENSE (0) 
   -  R vendor/github.com/Microsoft/go-winio/README.md (0) 
   -  A vendor/github.com/Microsoft/go-winio/archive/tar/LICENSE (27) 
   -  R vendor/github.com/Microsoft/go-winio/backup.go (0) 
   -  R vendor/github.com/Microsoft/go-winio/file.go (0) 
   -  R vendor/github.com/Microsoft/go-winio/fileinfo.go (0) 
   -  R vendor/github.com/Microsoft/go-winio/pipe.go (0) 
   -  R vendor/github.com/Microsoft/go-winio/privilege.go (0) 
   -  R vendor/github.com/Microsoft/go-winio/reparse.go (0) 
   -  R vendor/github.com/Microsoft/go-winio/sd.go (0) 
   -  R vendor/github.com/Microsoft/go-winio/syscall.go (0) 
   -  R vendor/github.com/Microsoft/go-winio/zsyscall.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/.gitignore (0) 
   -  R vendor/github.com/Sirupsen/logrus/.travis.yml (0) 
   -  R vendor/github.com/Sirupsen/logrus/CHANGELOG.md (0) 
   -  R vendor/github.com/Sirupsen/logrus/LICENSE (0) 
   -  R vendor/github.com/Sirupsen/logrus/README.md (0) 
   -  R vendor/github.com/Sirupsen/logrus/doc.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/entry.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/exported.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/formatter.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/hooks.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/json_formatter.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/logger.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/logrus.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/terminal_bsd.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/terminal_linux.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/terminal_notwindows.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/terminal_solaris.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/terminal_windows.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/text_formatter.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/writer.go (0) 
   -  R vendor/github.com/ceph/go-ceph/LICENSE (0) 
   -  R vendor/github.com/ceph/go-ceph/rados/conn.go (0) 
   -  R vendor/github.com/ceph/go-ceph/rados/doc.go (0) 
   -  R vendor/github.com/ceph/go-ceph/rados/ioctx.go (0) 
   -  R vendor/github.com/ceph/go-ceph/rados/rados.go (0) 
   -  R vendor/github.com/ceph/go-ceph/rbd/doc.go (0) 
   -  R vendor/github.com/ceph/go-ceph/rbd/rbd.go (0) 
   -  A vendor/github.com/coreos/go-systemd/LICENSE (191) 
   -  R vendor/github.com/coreos/go-systemd/activation/files.go (0) 
   -  R vendor/github.com/coreos/go-systemd/activation/listeners.go (0) 
   -  R vendor/github.com/coreos/go-systemd/activation/packetconns.go (0) 
   -  R vendor/github.com/docker/go-connections/LICENSE (2) 
   -  R vendor/github.com/docker/go-connections/sockets/README.md (0) 
   -  R vendor/github.com/docker/go-connections/sockets/inmem_socket.go (0) 
   -  R vendor/github.com/docker/go-connections/sockets/proxy.go (0) 
   -  R vendor/github.com/docker/go-connections/sockets/sockets.go (0) 
   -  R vendor/github.com/docker/go-connections/sockets/sockets_unix.go (0) 
   -  R vendor/github.com/docker/go-connections/sockets/sockets_windows.go (0) 
   -  R vendor/github.com/docker/go-connections/sockets/tcp_socket.go (0) 
   -  R vendor/github.com/docker/go-connections/sockets/unix_socket.go (2) 
   -  R vendor/github.com/gorilla/context/.travis.yml (0) 
   -  R vendor/github.com/gorilla/context/LICENSE (0) 
   -  R vendor/github.com/gorilla/context/README.md (0) 
   -  R vendor/github.com/gorilla/context/context.go (0) 
   -  R vendor/github.com/gorilla/context/doc.go (0) 
   -  R vendor/github.com/gorilla/mux/.travis.yml (0) 
   -  R vendor/github.com/gorilla/mux/LICENSE (0) 
   -  R vendor/github.com/gorilla/mux/README.md (0) 
   -  R vendor/github.com/gorilla/mux/doc.go (0) 
   -  R vendor/github.com/gorilla/mux/mux.go (0) 
   -  R vendor/github.com/gorilla/mux/regexp.go (0) 
   -  R vendor/github.com/gorilla/mux/route.go (0) 
   -  R vendor/github.com/inconshreveable/mousetrap/LICENSE (0) 
   -  R vendor/github.com/inconshreveable/mousetrap/README.md (0) 
   -  R vendor/github.com/inconshreveable/mousetrap/trap_others.go (0) 
   -  R vendor/github.com/inconshreveable/mousetrap/trap_windows.go (0) 
   -  R vendor/github.com/inconshreveable/mousetrap/trap_windows_1.4.go (0) 
   -  A vendor/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/Sirupsen/logrus/LICENSE (21) 
   -  A vendor/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/codegangsta/cli/LICENSE (21) 
   -  A vendor/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/coreos/go-systemd/LICENSE (191) 
   -  A vendor/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/docker/docker/pkg/symlink/LICENSE.APACHE (191) 
   -  A vendor/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/docker/docker/pkg/symlink/LICENSE.BSD (27) 
   -  A vendor/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/docker/go-units/LICENSE (191) 
   -  A vendor/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/godbus/dbus/LICENSE (25) 
   -  A vendor/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/specs/LICENSE (191) 
   -  A vendor/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/seccomp/libseccomp-golang/LICENSE (22) 
   -  A vendor/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/vishvananda/netlink/LICENSE (192) 
   -  R vendor/github.com/opencontainers/runc/LICENSE (0) 
   -  R vendor/github.com/opencontainers/runc/NOTICE (0) 
   -  R vendor/github.com/opencontainers/runc/libcontainer/user/MAINTAINERS (0) 
   -  R vendor/github.com/opencontainers/runc/libcontainer/user/lookup.go (0) 
   -  R vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go (0) 
   -  R vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unsupported.go (0) 
   -  R vendor/github.com/opencontainers/runc/libcontainer/user/user.go (0) 
   -  R vendor/github.com/satori/go.uuid/.travis.yml (2) 
   -  R vendor/github.com/satori/go.uuid/LICENSE (2) 
   -  R vendor/github.com/satori/go.uuid/README.md (2) 
   -  A vendor/github.com/satori/go.uuid/codec.go (206) 
   -  A vendor/github.com/satori/go.uuid/generator.go (239) 
   -  A vendor/github.com/satori/go.uuid/sql.go (78) 
   -  A vendor/github.com/satori/go.uuid/uuid.go (161) 
   -  R vendor/github.com/spf13/cobra/.gitignore (0) 
   -  R vendor/github.com/spf13/cobra/.mailmap (0) 
   -  R vendor/github.com/spf13/cobra/.travis.yml (0) 
   -  R vendor/github.com/spf13/cobra/LICENSE.txt (0) 
   -  R vendor/github.com/spf13/cobra/README.md (0) 
   -  R vendor/github.com/spf13/cobra/bash_completions.go (0) 
   -  R vendor/github.com/spf13/cobra/bash_completions.md (0) 
   -  R vendor/github.com/spf13/cobra/cobra.go (0) 
   -  R vendor/github.com/spf13/cobra/command.go (0) 
   -  R vendor/github.com/spf13/cobra/command_notwin.go (0) 
   -  R vendor/github.com/spf13/cobra/command_win.go (0) 
   -  R vendor/github.com/spf13/pflag/.travis.yml (0) 
   -  R vendor/github.com/spf13/pflag/LICENSE (0) 
   -  R vendor/github.com/spf13/pflag/README.md (0) 
   -  R vendor/github.com/spf13/pflag/bool.go (0) 
   -  R vendor/github.com/spf13/pflag/count.go (0) 
   -  R vendor/github.com/spf13/pflag/duration.go (0) 
   -  R vendor/github.com/spf13/pflag/flag.go (0) 
   -  R vendor/github.com/spf13/pflag/float32.go (0) 
   -  R vendor/github.com/spf13/pflag/float64.go (0) 
   -  R vendor/github.com/spf13/pflag/golangflag.go (0) 
   -  R vendor/github.com/spf13/pflag/int.go (0) 
   -  R vendor/github.com/spf13/pflag/int32.go (0) 
   -  R vendor/github.com/spf13/pflag/int64.go (0) 
   -  R vendor/github.com/spf13/pflag/int8.go (0) 
   -  R vendor/github.com/spf13/pflag/int_slice.go (0) 
   -  R vendor/github.com/spf13/pflag/ip.go (0) 
   -  R vendor/github.com/spf13/pflag/ipmask.go (0) 
   -  R vendor/github.com/spf13/pflag/ipnet.go (0) 
   -  R vendor/github.com/spf13/pflag/string.go (0) 
   -  R vendor/github.com/spf13/pflag/string_slice.go (0) 
   -  R vendor/github.com/spf13/pflag/uint.go (0) 
   -  R vendor/github.com/spf13/pflag/uint16.go (0) 
   -  R vendor/github.com/spf13/pflag/uint32.go (0) 
   -  R vendor/github.com/spf13/pflag/uint64.go (0) 
   -  R vendor/github.com/spf13/pflag/uint8.go (0) 
   -  A vendor/golang.org/x/net/AUTHORS (3) 
   -  A vendor/golang.org/x/net/CONTRIBUTORS (3) 
   -  A vendor/golang.org/x/net/LICENSE (27) 
   -  A vendor/golang.org/x/net/PATENTS (22) 
   -  R vendor/golang.org/x/net/context/context.go (2) 
   -  R vendor/golang.org/x/net/proxy/direct.go (0) 
   -  R vendor/golang.org/x/net/proxy/per_host.go (0) 
   -  R vendor/golang.org/x/net/proxy/proxy.go (2) 
   -  R vendor/golang.org/x/net/proxy/socks5.go (0) 
   -  A vendor/golang.org/x/sys/AUTHORS (3) 
   -  A vendor/golang.org/x/sys/CONTRIBUTORS (3) 
   -  A vendor/golang.org/x/sys/LICENSE (27) 
   -  A vendor/golang.org/x/sys/PATENTS (22) 
   -  A vendor/golang.org/x/sys/unix/.gitignore (2) 
   -  A vendor/golang.org/x/sys/unix/README.md (173) 
   -  A vendor/golang.org/x/sys/unix/affinity_linux.go (124) 
   -  A vendor/golang.org/x/sys/unix/aliases.go (14) 
   -  A vendor/golang.org/x/sys/unix/asm_aix_ppc64.s (17) 
   -  A vendor/golang.org/x/sys/unix/asm_darwin_386.s (29) 
   -  A vendor/golang.org/x/sys/unix/asm_darwin_amd64.s (29) 
   -  A vendor/golang.org/x/sys/unix/asm_darwin_arm.s (30) 
   -  A vendor/golang.org/x/sys/unix/asm_darwin_arm64.s (30) 
   -  A vendor/golang.org/x/sys/unix/asm_dragonfly_amd64.s (29) 
   -  A vendor/golang.org/x/sys/unix/asm_freebsd_386.s (29) 
   -  A vendor/golang.org/x/sys/unix/asm_freebsd_amd64.s (29) 
   -  A vendor/golang.org/x/sys/unix/asm_freebsd_arm.s (29) 
   -  A vendor/golang.org/x/sys/unix/asm_linux_386.s (65) 
   -  A vendor/golang.org/x/sys/unix/asm_linux_amd64.s (57) 
   -  A vendor/golang.org/x/sys/unix/asm_linux_arm.s (56) 
   -  A vendor/golang.org/x/sys/unix/asm_linux_arm64.s (52) 
   -  A vendor/golang.org/x/sys/unix/asm_linux_mips64x.s (56) 
   -  A vendor/golang.org/x/sys/unix/asm_linux_mipsx.s (54) 
   -  A vendor/golang.org/x/sys/unix/asm_linux_ppc64x.s (56) 
   -  A vendor/golang.org/x/sys/unix/asm_linux_s390x.s (56) 
   -  A vendor/golang.org/x/sys/unix/asm_netbsd_386.s (29) 
   -  A vendor/golang.org/x/sys/unix/asm_netbsd_amd64.s (29) 
   -  A vendor/golang.org/x/sys/unix/asm_netbsd_arm.s (29) 
   -  A vendor/golang.org/x/sys/unix/asm_openbsd_386.s (29) 
   -  A vendor/golang.org/x/sys/unix/asm_openbsd_amd64.s (29) 
   -  A vendor/golang.org/x/sys/unix/asm_openbsd_arm.s (29) 
   -  A vendor/golang.org/x/sys/unix/asm_solaris_amd64.s (17) 
   -  A vendor/golang.org/x/sys/unix/bluetooth_linux.go (35) 
   -  A vendor/golang.org/x/sys/unix/cap_freebsd.go (195) 
   -  A vendor/golang.org/x/sys/unix/constants.go (13) 
   -  A vendor/golang.org/x/sys/unix/dev_aix_ppc.go (27) 
   -  A vendor/golang.org/x/sys/unix/dev_aix_ppc64.go (29) 
   -  A vendor/golang.org/x/sys/unix/dev_darwin.go (24) 
   -  A vendor/golang.org/x/sys/unix/dev_dragonfly.go (30) 
   -  A vendor/golang.org/x/sys/unix/dev_freebsd.go (30) 
   -  A vendor/golang.org/x/sys/unix/dev_linux.go (42) 
   -  A vendor/golang.org/x/sys/unix/dev_netbsd.go (29) 
   -  A vendor/golang.org/x/sys/unix/dev_openbsd.go (29) 
   -  A vendor/golang.org/x/sys/unix/dirent.go (17) 
   -  A vendor/golang.org/x/sys/unix/endian_big.go (9) 
   -  A vendor/golang.org/x/sys/unix/endian_little.go (9) 
   -  A vendor/golang.org/x/sys/unix/env_unix.go (31) 
   -  A vendor/golang.org/x/sys/unix/errors_freebsd_386.go (227) 
   -  A vendor/golang.org/x/sys/unix/errors_freebsd_amd64.go (227) 
   -  A vendor/golang.org/x/sys/unix/errors_freebsd_arm.go (226) 
   -  A vendor/golang.org/x/sys/unix/fcntl.go (32) 
   -  A vendor/golang.org/x/sys/unix/fcntl_linux_32bit.go (13) 
   -  A vendor/golang.org/x/sys/unix/gccgo.go (62) 
   -  A vendor/golang.org/x/sys/unix/gccgo_c.c (39) 
   -  A vendor/golang.org/x/sys/unix/gccgo_linux_amd64.go (20) 
   -  A vendor/golang.org/x/sys/unix/ioctl.go (30) 
   -  A vendor/golang.org/x/sys/unix/mkall.sh (204) 
   -  A vendor/golang.org/x/sys/unix/mkerrors.sh (0) 
   -  A vendor/golang.org/x/sys/unix/mkpost.go (0) 
   -  A vendor/golang.org/x/sys/unix/mksyscall.pl (0) 
   -  A vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.pl (0) 
   -  A vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.pl (0) 
   -  A vendor/golang.org/x/sys/unix/mksyscall_solaris.pl (0) 
   -  A vendor/golang.org/x/sys/unix/mksysctl_openbsd.pl (0) 
   -  A vendor/golang.org/x/sys/unix/mksysnum_darwin.pl (0) 
   -  A vendor/golang.org/x/sys/unix/mksysnum_dragonfly.pl (0) 
   -  A vendor/golang.org/x/sys/unix/mksysnum_freebsd.pl (0) 
   -  A vendor/golang.org/x/sys/unix/mksysnum_netbsd.pl (0) 
   -  A vendor/golang.org/x/sys/unix/mksysnum_openbsd.pl (0) 
   -  A vendor/golang.org/x/sys/unix/openbsd_pledge.go (0) 
   -  A vendor/golang.org/x/sys/unix/openbsd_unveil.go (0) 
   -  A vendor/golang.org/x/sys/unix/pagesize_unix.go (0) 
   -  A vendor/golang.org/x/sys/unix/race.go (0) 
   -  A vendor/golang.org/x/sys/unix/race0.go (0) 
   -  A vendor/golang.org/x/sys/unix/sockcmsg_linux.go (0) 
   -  A vendor/golang.org/x/sys/unix/sockcmsg_unix.go (0) 

Patch Links:
   
   - https://github.com/gostor/gotgt/pull/75.patch
   - https://github.com/gostor/gotgt/pull/75.diff

**Comment by carmark** [comment]
@tpaullee The golang's vendor tool is always change, and `godep` is depreciated, so I use the latest vendor tool `dep` to manage it.

**Comment by orzhang** [comment]
finally. we can use dep instead of godep. 👍

**Comment by carmark** [comment]
@orzhang fixed the travis test issue, could be reviewed now.

**Pull request merged**
