### PR TITLE
fix(state): reset the CurrentHostIP on closed iscsi connection

### PR DESCRIPTION
**Pull request by prateekpandey14**
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>

PR tries to fix the issue with iscsi connection, in case k8s Node is shutdown abruptly, ending up not allowing the reschedule  application pod to mount the volume again.

PR reset the CurrentHostIP in case of connection state is closed and set the state as closed in case of any readdata errors happens on IOSTATE_RX_BHS state.

More info: https://github.com/openebs/jiva-operator/issues/125

### CODE REVIEW

**Comment by carmark** [comment]
LGTM, thanks

**Comment by prateekpandey14** [comment]
Thanks @carmark for fast reviews and merge. Can you pls create a new tag with this changes.

**Comment by carmark** [comment]
Sure, no prolem. @prateekpandey14

**Comment by carmark** [comment]
done, please try it. @prateekpandey14

**Pull request merged**
